### ISSUE TITLE
Crash when using singlehtml sphinx builder

### ISSUE THREAD

**Issue by rikardn** [jupyter/jupyter-sphinx#126]
I try to render the following minimal rst:

```
.. jupyter-execute::

    print("Hello world!")
```

with the following sphinx command:

```
sphinx-build -c source -D master_doc=test -b singlehtml source . source/test.rst
```

And this minimal conf.py

```python
extensions = ['jupyter_sphinx']
```

It crashes with the following log:

```
# Sphinx version: 2.4.4
# Python version: 3.7.5 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.2
# Last messages:
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   assembling single document...
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (2.4.4) from /home/rikard/.local/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /home/rikard/.local/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /home/rikard/.local/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /home/rikard/.local/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /home/rikard/.local/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /home/rikard/.local/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/rikard/.local/lib/python3.7/site-packages/alabaster/__init__.py
#   jupyter_sphinx (0.2.4) from /home/rikard/.local/lib/python3.7/site-packages/jupyter_sphinx/__init__.py
Traceback (most recent call last):
  File "/home/rikard/.local/lib/python3.7/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/home/rikard/.local/lib/python3.7/site-packages/sphinx/application.py", line 346, in build
    self.builder.build_specific(filenames)
  File "/home/rikard/.local/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 288, in build_specific
    summary=__('%d source files given on command line') % len(to_write))
  File "/home/rikard/.local/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/rikard/.local/lib/python3.7/site-packages/sphinx/builders/singlehtml.py", line 159, in write
    doctree = self.assemble_doctree()
  File "/home/rikard/.local/lib/python3.7/site-packages/sphinx/builders/singlehtml.py", line 83, in assemble_doctree
    self.env.resolve_references(tree, master, self)
  File "/home/rikard/.local/lib/python3.7/site-packages/sphinx/environment/__init__.py", line 571, in resolve_references
    self.apply_post_transforms(doctree, fromdocname)
  File "/home/rikard/.local/lib/python3.7/site-packages/sphinx/environment/__init__.py", line 583, in apply_post_transforms
    transformer.apply_transforms()
  File "/home/rikard/.local/lib/python3.7/site-packages/sphinx/transforms/__init__.py", line 86, in apply_transforms
    super().apply_transforms()
  File "/home/rikard/.local/lib/python3.7/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/rikard/.local/lib/python3.7/site-packages/jupyter_sphinx/ast.py", line 437, in apply
    attach_outputs(output_nodes, cell_node, thebe_config, cell_node.cm_language)
AttributeError: 'JupyterCellNode' object has no attribute 'cm_language'
```

If I use the default `html` builder it works fine.

**Comment by akhmerov** [comment]
Seems to be a regression introduced by #107 (at least I don't see this in v0.2.3). @choldgraf do you know what it could be?

**Comment by choldgraf** [comment]
hmmm - maybe? Could it be that post-transforms are applied differently in a singlepage html context?

**Comment by AdriaanRol** [comment]
I have the exact same issue. 
Strange thing is that it works fine when building locally, but it fails when building on readthedocs. 

I have not produced a minimal working example, but the configuration is similar to what @rikardn set up. I have added `jupyter_sphinx` to the extension in conf.py added `jupyter_sphinx` to the pip requirements and use a regular `.. jupyter-execute::` directive. 

I assume there must be some kind of difference in the environments when I build locally and when I build on ReadTheDocs . 

I was able to resolve the issue by rolling back to v0.2.3.

**Comment by abhigyanprksh** [comment]
I had a similar issue: https://github.com/jupyter/jupyter-sphinx/issues/128
The build was successful with v0.2.3, however my widgets are not rendering. It was working fine locally. Are there any additional dependencies?

**Comment by akhmerov** [comment]
@abhigyanprksh to keep the discussion focused, please ask questions unrelated to the topic of singlehtml being broken in a separate appropriate issue.

**Comment by abhigyanprksh** [comment]
Sure, I will create a new issue for that.

**Comment by akhmerov** [comment]
Hmm, the plot thickens: I have verified that the transform `ExecuteJupyterCells` (which executes the notebook and populates the cells with `cm_language`) is correctly applied, but when the `CellOutputsToNodes` is called, `cm_language` is gone.

**Comment by Julian** [comment]
Same issue here, which I wouldn't comment for, but just want to mention:

> I have the exact same issue.
Strange thing is that it works fine when building locally, but it fails when building on readthedocs.

It definitely fails here locally as well, as long as I explicitly use the `singlehtml` builder. The RTD builder is a bit different, they have their own custom single HTML builder, but yeah the normal default singlehtml builder definitely fails for me as well when jupyter-sphinx is enabled with the same traceback as the one I see in RTD.

(For a temporary workaround, in case anyone needs it, I guess I'm going to disable the single HTML builder in RTD :/... which you can do with the `formats` parameter in `.readthedocs.yml`).

**Comment by basnijholt** [comment]
We're seeing this issue in [Adaptive](https://github.com/python-adaptive/adaptive/) too [[build](https://readthedocs.org/projects/adaptive/builds/11615532/)].

**Comment by domfournier** [comment]
Following up on @Julian work around, for the other neophytes like me:
Here is what I added to the `readthedocs.yml` to make it work without downgrading to 0.2.3.

``sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true``
